apiVersion: v1
kind: ConfigMap
metadata:
  name: endpoints
data:
  mongo: mongodb://env:27017
  amqp: amqp://guest:guest@env:5672/
  ai: env:18001
  auth: auth:8081
  car: car:8081
  blob: blob:8081
  trip: rental:8081
  profile: rental:8081
  redis: redis:6379
