apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: public.ecr.aws/l4j6s3h2/coolcar:auth-1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: mongo
                  name: endpoints
            - name: WECHAT_APP_ID
              valueFrom:
                secretKeyRef:
                  key: appid
                  name: wechat
            - name: WECHAT_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: appsecret
                  name: wechat
            - name: PRIVATE_KEY_FILE
              value: /sec/private.key
          volumeMounts:
            - mountPath: /sec
              name: auth
              readOnly: true
      volumes:
        - name: auth
          secret:
            secretName: auth
            items:
              - key: privatekey
                path: private.key

---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - name: grpc
      protocol: TCP
      port: 8081
  type: ClusterIP
