apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: public.ecr.aws/l4j6s3h2/coolcar:auth-1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: mongo
                  name: endpoints
            - name: WECHAT_APP_ID
              valueFrom:
                secretKeyRef:
                  key: appid
                  name: wechat
            - name: WECHAT_APP_SECRET
              valueFrom:
                secretKeyRef:
                  key: appsecret
                  name: wechat

---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - name: http
      protocol: TCP
      port: 8080
  type: ClusterIP
