apiVersion: apps/v1
kind: Deployment
metadata:
  name: car
  labels:
    app: car
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car
  template:
    metadata:
      labels:
        app: car
        version: v1.2
    spec:
      containers:
        - name: car
          image: public.ecr.aws/qok1oq21/coolcar:car-1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: mongo
                  name: endpoints
            - name: AMQP_URL
              valueFrom:
                configMapKeyRef:
                  key: amqp
                  name: endpoints
            - name: CAR_ADDR
              valueFrom:
                configMapKeyRef:
                  key: car
                  name: endpoints
            - name: TRIP_ADDR
              valueFrom:
                configMapKeyRef:
                  key: trip
                  name: endpoints
            - name: AI_ADDR
              valueFrom:
                configMapKeyRef:
                  key: ai
                  name: endpoints
            - name: REDIS_ADDR
              valueFrom:
                configMapKeyRef:
                  key: redis
                  name: endpoints
          livenessProbe:
            exec:
              command: [ "/bin/grpc-health-probe", "-addr=:8081" ]
            initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: car
spec:
  selector:
    app: car
  ports:
    - name: grpc
      protocol: TCP
      port: 8081
    - name: http
      protocol: TCP
      port: 8080
  type: ClusterIP
