apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob
  labels:
    app: blob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob
  template:
    metadata:
      labels:
        app: blob
        version: v1.2
    spec:
      containers:
        - name: blob
          image: public.ecr.aws/l4j6s3h2/coolcar:blob-1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  key: mongo
                  name: endpoints
            - name: AWS_SEC_ID
              valueFrom:
                secretKeyRef:
                  key: secid
                  name: s3
            - name: AWS_SEC_KEY
              valueFrom:
                secretKeyRef:
                  key: seckey
                  name: s3
          livenessProbe:
            exec:
              command: [ "/bin/grpc-health-probe", "-addr=:8081" ]
            initialDelaySeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: blob
spec:
  selector:
    app: blob
  ports:
    - name: grpc
      protocol: TCP
      port: 8081
  type: ClusterIP
