apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
        version: v1.1
    spec:
      containers:
      - name: gateway
        image: public.ecr.aws/qok1oq21/coolcar:gateway-1.1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        env:
          - name: AUTH_ADDR
            valueFrom:
              configMapKeyRef:
                key: auth
                name: endpoints
          - name: TRIP_ADDR
            valueFrom:
              configMapKeyRef:
                key: trip
                name: endpoints
          - name: PROFILE_ADDR
            valueFrom:
              configMapKeyRef:
                key: profile
                name: endpoints
          - name: CAR_ADDR
            valueFrom:
              configMapKeyRef:
                key: car
                name: endpoints
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5


---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 8080
  type: ClusterIP
