apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: public.ecr.aws/l4j6s3h2/coolcar:gateway
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 8080
  type: LoadBalancer
